server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # User Service Routes
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=2

            # Product Service Routes  
            - id: product-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/products/**
              filters:
                - StripPrefix=2

            # Order Service Routes
            - id: order-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/orders/**
              filters:
                - StripPrefix=2
                - name: AuthenticationFilter

          default-filters:
            - name: GlobalCorsFilter

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: mySecretKey
  expiration: 86400000
